// This file is auto-generated by tools/codegen.py
// DO NOT EDIT — all changes will be overwritten.

#include "server/registry/handler_registry.hpp"
#include "built_in/tool_base.hpp"

#include "built_in/tools/meta/call_tool.hpp"
#include "built_in/tools/meta/get_tool_schema.hpp"
#include "built_in/tools/meta/godot_info.hpp"
#include "built_in/tools/meta/list_tool_categories.hpp"
#include "built_in/tools/meta/list_tools.hpp"
#include "built_in/tools/scene/branch_to_scene.hpp"
#include "built_in/tools/scene/close_scene.hpp"
#include "built_in/tools/scene/create_scene.hpp"
#include "built_in/tools/scene/delete_scene.hpp"
#include "built_in/tools/scene/get_open_scene_roots.hpp"
#include "built_in/tools/scene/get_open_scenes.hpp"
#include "built_in/tools/scene/instantiate_scene.hpp"
#include "built_in/tools/scene/is_scene_dirty.hpp"
#include "built_in/tools/scene/mark_scene_unsaved.hpp"
#include "built_in/tools/scene/open_scene.hpp"
#include "built_in/tools/scene/reload_scene.hpp"
#include "built_in/tools/scene/rename_scene.hpp"
#include "built_in/tools/scene/save_all_scenes.hpp"
#include "built_in/tools/scene/save_scene.hpp"
#include "built_in/tools/scene/save_scene_as.hpp"
#include "built_in/tools/scene/scene_to_branch.hpp"

namespace godot_mcp {

void register_itools(HandlerRegistry &reg) {
    auto tool_0 = std::make_unique<CallToolTool>();
    reg.register_tool(std::move(tool_0));

    auto tool_1 = std::make_unique<GetToolSchemaTool>();
    reg.register_tool(std::move(tool_1));

    auto tool_2 = std::make_unique<GodotInfoTool>();
    reg.register_tool(std::move(tool_2));

    auto tool_3 = std::make_unique<ListToolCategoriesTool>();
    reg.register_tool(std::move(tool_3));

    auto tool_4 = std::make_unique<ListToolsTool>();
    reg.register_tool(std::move(tool_4));

    auto tool_5 = std::make_unique<BranchToSceneTool>();
    reg.register_tool(std::move(tool_5));

    auto tool_6 = std::make_unique<CloseSceneTool>();
    reg.register_tool(std::move(tool_6));

    auto tool_7 = std::make_unique<CreateSceneTool>();
    reg.register_tool(std::move(tool_7));

    auto tool_8 = std::make_unique<DeleteSceneTool>();
    reg.register_tool(std::move(tool_8));

    auto tool_9 = std::make_unique<GetOpenSceneRootsTool>();
    reg.register_tool(std::move(tool_9));

    auto tool_10 = std::make_unique<GetOpenScenesTool>();
    reg.register_tool(std::move(tool_10));

    auto tool_11 = std::make_unique<InstantiateSceneTool>();
    reg.register_tool(std::move(tool_11));

    auto tool_12 = std::make_unique<IsSceneDirtyTool>();
    reg.register_tool(std::move(tool_12));

    auto tool_13 = std::make_unique<MarkSceneUnsavedTool>();
    reg.register_tool(std::move(tool_13));

    auto tool_14 = std::make_unique<OpenSceneTool>();
    reg.register_tool(std::move(tool_14));

    auto tool_15 = std::make_unique<ReloadSceneTool>();
    reg.register_tool(std::move(tool_15));

    auto tool_16 = std::make_unique<RenameSceneTool>();
    reg.register_tool(std::move(tool_16));

    auto tool_17 = std::make_unique<SaveAllScenesTool>();
    reg.register_tool(std::move(tool_17));

    auto tool_18 = std::make_unique<SaveSceneTool>();
    reg.register_tool(std::move(tool_18));

    auto tool_19 = std::make_unique<SaveSceneAsTool>();
    reg.register_tool(std::move(tool_19));

    auto tool_20 = std::make_unique<SceneToBranchTool>();
    reg.register_tool(std::move(tool_20));

}

} // namespace godot_mcp
