category: application
settings:
- name: application/boot_splash/bg_color
  type: 20
  type_name: Color
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/boot_splash/image
  type: 4
  type_name: String
  hint: 13
  hint_string: '*.png'
  basic: false
  restart: false
- name: application/boot_splash/minimum_display_time
  type: 2
  type_name: int
  hint: 1
  hint_string: 0,100,1,or_greater,suffix:ms
  basic: false
  restart: false
- name: application/boot_splash/show_image
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/boot_splash/stretch_mode
  type: 2
  type_name: int
  hint: 2
  hint_string: Disabled,Keep,Keep Width,Keep Height,Cover,Ignore
  basic: false
  restart: false
- name: application/boot_splash/use_filter
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/config/auto_accept_quit
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/config/custom_user_dir_name
  type: 4
  type_name: String
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/config/description
  type: 4
  type_name: String
  hint: 18
  hint_string: ''
  basic: false
  restart: false
- name: application/config/disable_project_settings_override
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/config/icon
  type: 4
  type_name: String
  hint: 13
  hint_string: '*.png,*.bmp,*.hdr,*.jpg,*.jpeg,*.svg,*.tga,*.exr,*.webp'
  basic: false
  restart: false
- name: application/config/macos_native_icon
  type: 4
  type_name: String
  hint: 13
  hint_string: '*.icns'
  basic: false
  restart: false
- name: application/config/name
  type: 4
  type_name: String
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/config/name_localized
  type: 27
  type_name: Dictionary
  hint: 33
  hint_string: ''
  basic: false
  restart: false
- name: application/config/project_settings_override
  type: 4
  type_name: String
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/config/quit_on_go_back
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/config/use_custom_user_dir
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/config/use_hidden_project_data_directory
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: true
- name: application/config/version
  type: 4
  type_name: String
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/config/windows_native_icon
  type: 4
  type_name: String
  hint: 13
  hint_string: '*.ico'
  basic: false
  restart: false
- name: application/run/delta_smoothing
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/run/disable_stderr
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/run/disable_stdout
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/run/enable_alt_space_menu
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/run/flush_stdout_on_print
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: true
- name: application/run/flush_stdout_on_print.debug
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: true
- name: application/run/frame_delay_msec
  type: 2
  type_name: int
  hint: 1
  hint_string: 0,100,1,or_greater
  basic: false
  restart: false
- name: application/run/load_shell_environment
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/run/low_processor_mode
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/run/low_processor_mode_sleep_usec
  type: 2
  type_name: int
  hint: 1
  hint_string: 0,33200,1,or_greater
  basic: false
  restart: false
- name: application/run/main_loop_type
  type: 4
  type_name: String
  hint: 0
  hint_string: ''
  basic: false
  restart: false
- name: application/run/main_scene
  type: 4
  type_name: String
  hint: 13
  hint_string: '*.tscn,*.scn,*.res'
  basic: false
  restart: false
- name: application/run/max_fps
  type: 2
  type_name: int
  hint: 1
  hint_string: 0,1000,1
  basic: false
  restart: false
- name: application/run/print_header
  type: 1
  type_name: bool
  hint: 0
  hint_string: ''
  basic: false
  restart: false
