// Layer 3 — Documentation query tools (existing + new)
GODOT_MCP_TOOL(SearchDocsTool, false)
GODOT_MCP_TOOL(GetClassInfoTool, false)
GODOT_MCP_TOOL(GetBestPracticesTool, false)
GODOT_MCP_TOOL(GetClassListTool, false)
GODOT_MCP_TOOL(GetInheritanceChainTool, false)
GODOT_MCP_TOOL(GetPropertyDocTool, false)
GODOT_MCP_TOOL(GetMethodDocTool, false)
GODOT_MCP_TOOL(GetEnumDocTool, false)
