class: Environment
inherits: Resource
properties:
- name: background_mode
  type: 2
  type_name: int
- name: background_color
  type: 20
  type_name: Color
- name: background_energy_multiplier
  type: 3
  type_name: float
- name: background_intensity
  type: 3
  type_name: float
- name: background_canvas_max_layer
  type: 2
  type_name: int
- name: background_camera_feed_id
  type: 2
  type_name: int
- name: sky
  type: 24
  type_name: Object
  class_name: Sky
- name: sky_custom_fov
  type: 3
  type_name: float
- name: sky_rotation
  type: 9
  type_name: Vector3
- name: ambient_light_source
  type: 2
  type_name: int
- name: ambient_light_color
  type: 20
  type_name: Color
- name: ambient_light_sky_contribution
  type: 3
  type_name: float
- name: ambient_light_energy
  type: 3
  type_name: float
- name: reflected_light_source
  type: 2
  type_name: int
- name: tonemap_mode
  type: 2
  type_name: int
- name: tonemap_exposure
  type: 3
  type_name: float
- name: tonemap_white
  type: 3
  type_name: float
- name: tonemap_agx_white
  type: 3
  type_name: float
- name: tonemap_agx_contrast
  type: 3
  type_name: float
- name: ssr_enabled
  type: 1
  type_name: bool
- name: ssr_max_steps
  type: 2
  type_name: int
- name: ssr_fade_in
  type: 3
  type_name: float
- name: ssr_fade_out
  type: 3
  type_name: float
- name: ssr_depth_tolerance
  type: 3
  type_name: float
- name: ssao_enabled
  type: 1
  type_name: bool
- name: ssao_radius
  type: 3
  type_name: float
- name: ssao_intensity
  type: 3
  type_name: float
- name: ssao_power
  type: 3
  type_name: float
- name: ssao_detail
  type: 3
  type_name: float
- name: ssao_horizon
  type: 3
  type_name: float
- name: ssao_sharpness
  type: 3
  type_name: float
- name: ssao_light_affect
  type: 3
  type_name: float
- name: ssao_ao_channel_affect
  type: 3
  type_name: float
- name: ssil_enabled
  type: 1
  type_name: bool
- name: ssil_radius
  type: 3
  type_name: float
- name: ssil_intensity
  type: 3
  type_name: float
- name: ssil_sharpness
  type: 3
  type_name: float
- name: ssil_normal_rejection
  type: 3
  type_name: float
- name: sdfgi_enabled
  type: 1
  type_name: bool
- name: sdfgi_use_occlusion
  type: 1
  type_name: bool
- name: sdfgi_read_sky_light
  type: 1
  type_name: bool
- name: sdfgi_bounce_feedback
  type: 3
  type_name: float
- name: sdfgi_cascades
  type: 2
  type_name: int
- name: sdfgi_min_cell_size
  type: 3
  type_name: float
- name: sdfgi_cascade0_distance
  type: 3
  type_name: float
- name: sdfgi_max_distance
  type: 3
  type_name: float
- name: sdfgi_y_scale
  type: 2
  type_name: int
- name: sdfgi_energy
  type: 3
  type_name: float
- name: sdfgi_normal_bias
  type: 3
  type_name: float
- name: sdfgi_probe_bias
  type: 3
  type_name: float
- name: glow_enabled
  type: 1
  type_name: bool
- name: glow_levels/1
  type: 3
  type_name: float
- name: glow_levels/2
  type: 3
  type_name: float
- name: glow_levels/3
  type: 3
  type_name: float
- name: glow_levels/4
  type: 3
  type_name: float
- name: glow_levels/5
  type: 3
  type_name: float
- name: glow_levels/6
  type: 3
  type_name: float
- name: glow_levels/7
  type: 3
  type_name: float
- name: glow_normalized
  type: 1
  type_name: bool
- name: glow_intensity
  type: 3
  type_name: float
- name: glow_strength
  type: 3
  type_name: float
- name: glow_mix
  type: 3
  type_name: float
- name: glow_bloom
  type: 3
  type_name: float
- name: glow_blend_mode
  type: 2
  type_name: int
- name: glow_hdr_threshold
  type: 3
  type_name: float
- name: glow_hdr_scale
  type: 3
  type_name: float
- name: glow_hdr_luminance_cap
  type: 3
  type_name: float
- name: glow_map_strength
  type: 3
  type_name: float
- name: glow_map
  type: 24
  type_name: Object
  class_name: Texture2D
- name: fog_enabled
  type: 1
  type_name: bool
- name: fog_mode
  type: 2
  type_name: int
- name: fog_light_color
  type: 20
  type_name: Color
- name: fog_light_energy
  type: 3
  type_name: float
- name: fog_sun_scatter
  type: 3
  type_name: float
- name: fog_density
  type: 3
  type_name: float
- name: fog_aerial_perspective
  type: 3
  type_name: float
- name: fog_sky_affect
  type: 3
  type_name: float
- name: fog_height
  type: 3
  type_name: float
- name: fog_height_density
  type: 3
  type_name: float
- name: fog_depth_curve
  type: 3
  type_name: float
- name: fog_depth_begin
  type: 3
  type_name: float
- name: fog_depth_end
  type: 3
  type_name: float
- name: volumetric_fog_enabled
  type: 1
  type_name: bool
- name: volumetric_fog_density
  type: 3
  type_name: float
- name: volumetric_fog_albedo
  type: 20
  type_name: Color
- name: volumetric_fog_emission
  type: 20
  type_name: Color
- name: volumetric_fog_emission_energy
  type: 3
  type_name: float
- name: volumetric_fog_gi_inject
  type: 3
  type_name: float
- name: volumetric_fog_anisotropy
  type: 3
  type_name: float
- name: volumetric_fog_length
  type: 3
  type_name: float
- name: volumetric_fog_detail_spread
  type: 3
  type_name: float
- name: volumetric_fog_ambient_inject
  type: 3
  type_name: float
- name: volumetric_fog_sky_affect
  type: 3
  type_name: float
- name: volumetric_fog_temporal_reprojection_enabled
  type: 1
  type_name: bool
- name: volumetric_fog_temporal_reprojection_amount
  type: 3
  type_name: float
- name: adjustment_enabled
  type: 1
  type_name: bool
- name: adjustment_brightness
  type: 3
  type_name: float
- name: adjustment_contrast
  type: 3
  type_name: float
- name: adjustment_saturation
  type: 3
  type_name: float
- name: adjustment_color_correction
  type: 24
  type_name: Object
  class_name: Texture2D,Texture3D
description: ''
aliases: []
