class: WorldEnvironment
inherits: Node
properties:
- name: environment
  type: 24
  type_name: Object
- name: camera_attributes
  type: 24
  type_name: Object
- name: compositor
  type: 24
  type_name: Object
description: A node that defines the environment for a scene.
aliases: []
