#!/usr/bin/env python3
"""
codegen.py — ITool 自动注册代码生成器

扫描 source-dir 下所有 .hpp 文件，查找带有 `// @tool register` 注释的 ITool 子类，
提取类名和 `// @source <type>` 标记，生成 `generated_registration.cpp`。

用法:
    uv run python tools/codegen.py \\
        --source-dir extensions/src/built_in/tools \\
        --output build/generated/generated_registration.cpp
"""

import argparse
import os
import re
import sys


def find_tool_files(source_dir: str) -> list[dict]:
    """扫描 source_dir 下所有 .hpp 文件，提取工具信息。"""
    if not os.path.isdir(source_dir):
        return []

    tools = []

    for root, _dirs, files in os.walk(source_dir):
        for fname in sorted(files):
            if not fname.endswith(".hpp"):
                continue

            fpath = os.path.join(root, fname)
            with open(fpath, "r", encoding="utf-8") as f:
                content = f.read()

            if "// @tool register" not in content:
                continue

            lines = content.split("\n")
            has_register = False
            source_type = "built_in"
            class_name = None

            for i, line in enumerate(lines):
                stripped = line.strip()

                if stripped == "// @tool register":
                    has_register = True
                    continue

                m = re.match(r"^//\s*@source\s+(\S+)", stripped)
                if m:
                    source_type = m.group(1)
                    continue

                m = re.match(
                    r"^class\s+(\w+)\s*[:\n]",
                    stripped,
                )
                if m and class_name is None:
                    class_name = m.group(1)

            if has_register and class_name:
                # 计算相对路径用于 #include
                rel_path = os.path.relpath(fpath, source_dir).replace("\\", "/")

                include_path = os.path.relpath(fpath, os.path.join(source_dir, "..", "..", "src"))
                # 回退：直接用 source_dir 父路径
                # 更好的做法是用相对于 src/ 的路径
                # source_dir 是 .../src/built_in/tools
                # include 要从 src/ 开始： built_in/tools/...
                src_dir = os.path.normpath(os.path.join(source_dir, ".."))
                inc_path = os.path.relpath(fpath, src_dir).replace("\\", "/")

                tools.append({
                    "class_name": class_name,
                    "source": source_type,
                    "include_path": inc_path,
                })

    return tools


def generate_code(tools: list[dict]) -> str:
    """生成 generated_registration.cpp 内容。"""
    lines = [
        "// This file is auto-generated by tools/codegen.py",
        "// DO NOT EDIT — all changes will be overwritten.",
        "",
        '#include "server/registry/handler_registry.hpp"',
        '#include "built_in/tool_base.hpp"',
        "",
    ]

    # #include 每个工具头文件
    for t in tools:
        lines.append(f'#include "{t["include_path"]}"')
    lines.append("")

    lines.append("namespace godot_mcp {")
    lines.append("")
    lines.append("void register_itools(HandlerRegistry &reg) {")

    if not tools:
        lines.append("    // No ITool-registered tools found.")
    else:
        for t in tools:
            source_type = t["source"]
            lines.append(f'    auto tool = std::make_unique<{t["class_name"]}>();')
            lines.append("    (void)tool; // mark used")
            lines.append(f'    reg.register_tool(std::move(tool));')
            lines.append("")

    lines.append("}")
    lines.append("")
    lines.append("} // namespace godot_mcp")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate ITool registration code")
    parser.add_argument(
        "--source-dir",
        required=True,
        help="Directory to scan for tool .hpp files",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output file path for generated_registration.cpp",
    )
    args = parser.parse_args()

    tools = find_tool_files(args.source_dir)
    code = generate_code(tools)

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(code)

    print(f"[codegen] Found {len(tools)} tool(s), wrote {args.output}")


if __name__ == "__main__":
    main()
